name: pre-commit

on:
    push:
        branches: [$default-branch]
    pull_request:

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
                path: app
            - name: Install pre-commit
              run: pip install pre-commit
            - name: Install pre-commit
              working-directory: ./app
              run: |
                pre-commit run --show-diff-on-failure --colore=always --all-files
